### ISSUE TITLE
4K HEVC no video playback in Plex add-on for Kodi (Android)

### ISSUE THREAD

**Issue by iTorrek** [plexinc/plex-for-kodi#111]
Video glitch with 4k HEVC on Plex for kodi for android
[xml.txt](https://github.com/plexinc/plex-for-kodi/files/1012422/xml.txt)

Works fine with Plex for Android, fine with both Kodi for Windows and plex addon for kodi for windows. But no video playback on Plex add-on for Kodi in Android.

Android 5. Kodi 17.1

xml attached, log will be attached later

**Comment by ruuk** [comment]
Is the video OK when playing directly in Kodi on Android (ie. when not using Plex)?

**Comment by iTorrek** [comment]
Nope. So, looks like its Kodi's problem
