### ISSUE TITLE
Sometimes crashing on exit

### ISSUE THREAD

**Issue by keithah** [plexinc/plex-for-kodi#119]
@danjames92 has reported his ODROID-C2 crashes upon exit of the Plex addon.

Cannot reproduce this, but he gave me logs:
[Logs.zip](https://github.com/plexinc/plex-for-kodi/files/1235271/Logs.zip)

**Comment by danjames92** [comment]
The logs are from a Windows PC with clean installed Kodi V17.3.

**Comment by ruuk** [comment]
Should be fixed. Feel free to re-open if the issue is still there.
