### ISSUE TITLE
Can't change audio track

### ISSUE THREAD

**Issue by Jelmerb** [plexinc/plex-for-kodi#12]
Hi keithah,
I have kodi v17b6 installed on macOS 10.12.1. 
When I play a movie I can't change the audio language, and sometimes a different audio track is played than the audio track selected in the settings. 

log url: [](https://paste.ubuntu.com/23559508/)

**Comment by ruuk** [comment]
Confirmed. It seems changing the audio track only works when transcoding.

**Comment by ruuk** [comment]
Fixed with 1ff7d9c3ac9a36d8f4dbba95c802748079cbcfc3

**Comment by ruuk** [comment]
And wholly fixed with 4b950c46bd94fe2977a377693be5dcf46e144617 :)
