### ISSUE TITLE
Find a workaround to shut down the add-on when navigating to Kodi windows

### ISSUE THREAD

**Issue by pbathuk** [plexinc/plex-for-kodi#126]
As the title says, I find that unless I back out of the Plex addon fully (i.e. get the dialog to exit Plex) the controls within the rest of Kodi are Plex style, this reduces the WAF as we can't flick straight to live TV from playing a Plex video. 
Happy to provide logs etc if that would help.
Cheers

**Comment by ruuk** [comment]
I'm not familiar with the acronym WAF, but in any case, there is no other way to exit the add-on other than backing out fully. Anything that gets you to a Kodi screen without doing this leaves the add-on running. This is true of any skinned add-on.
Unfortunately Kodi does not give an add-on any indication that this has happened. This is really more of a Kodi bug as it shouldn't allow switching to other Kodi windows when a skinned add-on is open or alternatively it should provide some mechanism to signal an addon to shut itself down. 

I'm changing the title of the issue to reflect the need to find a possible workaround.

**Comment by pbathuk** [comment]
Sorry WAF is Wife Acceptance Factor :)

Cheers for looking into this, one thought I had, for my own situation at least was to rebind a button to run a script to take me to the front screen & close the script, but having limited python skills that might take me some time :) 
Ideally Kodi would report what screen / add-ons are in use and allow the user to kill the ones not in use (if desired).

**Comment by pbathuk** [comment]
So I have been thinking about this... For my usecase I am wondering if the following would work, and if you believe so then I can try it out and then we can see how it can be integrated...
Usecase : when leaving Plex add-on to use the TV guide / Live PVR Plex should stop running to ensure that control hands back to Kodi.. not sure if this is how you write a usecase... But hey ho you hopefully get the drift.

Potential workaround : on button press / key press run a small python script that will work out what the action to be taken is (i.e. load PVR / PVR guide) and if in a certain list / array then run the stopscript(plex.addon) (or what ever the command is.

I plan to link into the standard Kodi python inputs and assume that the current active window name / ID can be taken easily. I will write a test script and see if this works.

I will report back once I have something working/close to working and then you can provide guidance
