### ISSUE TITLE
Handling the Non-English or Empty MetaData Failed

### ISSUE THREAD

**Issue by kunilam** [plexinc/plex-for-kodi#13]
The addon handling the media (TV Shows/Movies/Music) with English MetaData fine. However, whenever it tries to handle the media with Non-English MetaData (such as Japanese or Chinese) or the media with empty metadata, it hangs, no matter whether it is music/tv shows/Movies, even home videos. 

I guess it is related to the unicode handling in the plugins. 

(P.S. Test with Kodi 16.1 and Kodi 17 at OSX 10.9.5)

**Comment by keithah** [comment]
Thanks for reporting @kunilam but please follow: https://forums.plex.tv/discussion/246912/reporting-plex-for-kodi-issues and post a log.

**Comment by kunilam** [comment]
Thanks, I attached the relevant lodi.log and PMS.log for your refs. Hope this may help
[log.zip](https://github.com/plexinc/plex-for-kodi/files/623364/log.zip)

**Comment by keithah** [comment]
Definitely looks like a bug with Unicode! @ruuk will need to take a look. Thanks for reporting!

**Comment by keithah** [comment]
This is fixed in the next release, which is .90 and will be available soon, likely tomorrow.

**Comment by keithah** [comment]
This is fixed on the forum, so closing out this ticket. Let me know if you still have issues.
