### ISSUE TITLE
Need ability to use 'native' Kodi skip forward/backword commands

### ISSUE THREAD

**Issue by tiny-e** [plexinc/plex-for-kodi#133]
The current UI design is cool for CEC people / people with basic remotes, I guess.  But, the current way of skipping around in a video adds 2X to 3X the amount of clicking to accomplish the same thing as the old jump forward/back function.  

Can there be an option added to use 'old school' or native Kodi skip behavior?

**Comment by solbu** [comment]
I support this request.
An option to use the kodi way of moving around a video stream would be nice.
