### ISSUE TITLE
latest update script.module.requests kills plex server connection

### ISSUE THREAD

**Issue by avenantsoftware** [plexinc/plex-for-kodi#137]
reported first here: https://github.com/beenje/script.module.requests/issues/17#issuecomment-343283017

latest update of the script.module.requests addon kills the plex for kodi addon, it is unable to connect to the plex server, have to revert to version 2.12.4, and disable automatic addon updates in kodi, if you want the plex for kodi addon to work again...

So who's going to fix it? script.module.requests coder says it's plex for kodi fault, lol, the usual blame shifting game or avoid support game lol..

**Comment by ruuk** [comment]
Fixed in version 0.1.3
