### ISSUE TITLE
Does not work with Leia / LibreELEC 9.0?

### ISSUE THREAD

**Issue by smoothquark** [plexinc/plex-for-kodi#138]
Hi! Looks like this is incompatible with LibreELEC 9.0? Hangs on signin. For some reason, My LibreELEC 8.2 With Kodi Krypton 17.5 does not play UHD videos - audio plays but blank screen, hence my reason to "upgrade" to LibreELEC 9.0, where it natively plays the videos OK (without HDR).

**Comment by ruuk** [comment]
As Leia is not yet released, it is not yet supported. I'm aware that there are some issues with Kodi 18, but they are not easily fixable without making the add-on incompatible with Kodi 16 (which still has a fairly large number of users). I'm closing this issue, but rest assured that there will be a compatible version sometime before Kodi 18 is released.

**Comment by smoothquark** [comment]
Thank you. Fingers crossed....
