### ISSUE TITLE
Launching the add-on from My Addons doesn't work

### ISSUE THREAD

**Issue by keithah** [plexinc/plex-for-kodi#14]
In Kodi v16.1, if you launch the add-on from My Addons it crashes or won't load.

**Comment by Enigma0** [comment]
I'm seeing the same in v17 beta. Seems like it doesn't launch at first but if I keep clicking on it, eventually it does launch.

**Comment by keithah** [comment]
According to the forum thread, if you favorite it and then make it a shortcut it should work, so try that? 

"To get it working, i added Plex to favourites, and then went in and added the shortcut menu via the favourites, instead of using the one placed under video add ons."

as a workaround until we can resolve this.
