### ISSUE TITLE
Plex for Kodi addon fails with Kodi 18/Libreelec test builds

### ISSUE THREAD

**Issue by frafall** [plexinc/plex-for-kodi#140]
Basically when starting it hangs on the three dots '...', I'm running [Libreelec Milhouse build](https://forum.kodi.tv/showthread.php?tid=298461) on a RPi2.

So, now it's running Kodi 17 without DVD playing or Kodi 18 without Plex :(

**Comment by gio00** [comment]
Yeah, same issue.
RPi3 osmc updated to kodi 18

**Comment by ruuk** [comment]
I'm closing this in favor of #146. While it is true that I am already working on compatibility, v18 has not even had an official alpha release.
