### ISSUE TITLE
Make compatible with Kodi v18 (Leia)

### ISSUE THREAD

**Issue by ruuk** [plexinc/plex-for-kodi#146]
As of this writing (Dec 28, 2017) there is not yet an public alpha release for Kodi v18, but I'm adding this issue is here to track progress of updating the addon to be compatible.

Please note, that while the add-on will certainly be working on v18 before the first stable release, v18 won't be officially supported until that time.

**Comment by iz8mbw** [comment]
Hi. Any news to support Kodi 18 for the Plex addon?

**Comment by ruuk** [comment]
Fixed
