### ISSUE TITLE
Workaround script for Intel 3,4 & 5th Gen resume with h.265

### ISSUE THREAD

**Issue by pbathuk** [plexinc/plex-for-kodi#147]
Hi,

Not sure if this sits here, but I use plex for kodi ALOT, like all my media needs (except live TV), however because I have a 4th Gen intel NUC there is a known issue where by resuming a h.265 file will crash kodi, plex for kodi, because it uses the same video engine, is also affected.

There is a simply workaround that can be used to get around this, I have implemented it in my player.py (from developer branch) and wanted to share, incase others have the same issue.

It requires : import time as it sleeps the script for 5 seconds, to ensure that the video has started.
Then its a simply change to the below def:

```python
def playVideo(self, video, resume=False, force_update=False, session_id=None, handler=None):
```
Changing the bottom line to : 
```python
  self._playVideo(0, force_update=force_update)
  if resume:
    time.sleep(5) 
    util.DEBUG_LOG('player skipping to resume offset')
    self.handler.seek(video.viewOffset.asInt())
```
I hope this helps some people.. the same could be implemented into kodi, but I am not sure how to edit that code yet...

Feel free to close this down if wrong / or delete etc. 
Would be interested to see if there is a smarter way todo the above to fix the above issue (referenced here: )

[https://forum.kodi.tv/showthread.php?tid=248859](https://forum.kodi.tv/showthread.php?tid=248859)
  
_(edited code formatting - ruuk)_

**Comment by ruuk** [comment]
That thread mentions Kodi 15.2. Currently only Kodi 16+ is supported for the add-on. What version of Kodi are you running?
It is possible the next version of the add-on will fix the issue, because I have added some changes to the timing of the initial seek. Other than that it's really something that needs to be fixed in Kodi if it's still an issue in the current version.

I'm closing this, but I'm still interested to know your Kodi version.

**Comment by pbathuk** [comment]
Hey, 
It actually impacts 17.x as well, I am running 17.6 and have the issue.
Thanks for looking at it.

Fyi the issue is actually a driver issue, which intel have accepted, however they won't fix it on the older gen models due it being out of development cycle, therefore I build this to work around that Dev bug.
