### ISSUE TITLE
Incomplete changelog.txt

### ISSUE THREAD

**Issue by johnmanko** [plexinc/plex-for-kodi#158]
Why doesn't the changelog.txt list the change that Plex now requires a Plex.tv account, even when the plex server is local?

https://github.com/plexinc/plex-for-kodi/commit/819229ce84ae6bad4ba99d65aa57b180e6b3ee4b#diff-e8800259c4985f4a73b0936128034c53

Please update the changelog.txt.  Thanks.

**Comment by ruuk** [comment]
There has been no change in this regard. The diff you linked shows the removal of the Plex Pass requirement, which is noted in the changelog.
