### ISSUE TITLE
Can't Access Shared Servers

### ISSUE THREAD

**Issue by clarenceb5** [plexinc/plex-for-kodi#159]
Plex for Kodi on Kodi 16 on Android TV 8.0.

When my home server is unavailable/offline I am unable to choose a shared server. I have many servers shared with me and when my home server is not available all servers are unavailable even my Plex Cloud Server.

I know the servers are online because I can access them from the Plex for Android TV app but not from Plex for Kodi.

**Comment by ruuk** [comment]
Fixed for next release.
