### ISSUE TITLE
Plugin behavior on Xbox ONE

### ISSUE THREAD

**Issue by ivlovric** [plexinc/plex-for-kodi#162]
There is an issue with plugin with currently latest Kodi 18 alpha for Xbox ONE. GUI elements are not displayed at all and with blind navigation I was able to start playback, but there are also control elements that are diplayed over top of playing media without ability to hide them.
Since this is new platform, maybe there is more that needs to be done on plugin side.
Thanks.

**Comment by ruuk** [comment]
There is already an issue regarding compatibility with the Kodi 18 alpha version,  so closing this.
