### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by str80** [plexinc/plex-for-kodi#163]
Can you help me out here. I am trying to use indigo tool function gitbrowser in kodi it's asking me for your username, but I can not find it, when I enter the name "plex" my search come up empty
Also it has the function search for ID but I can not find it either
If you can facilitate me your username or Id would be appreciated. 
I would like to download your repo pled for kodi

Thank you

**Comment by ruuk** [comment]
Sorry, I can't help you with that. Issues here should be related to the Plex for Kodi software itself. It sounds like your issue is related to other software. Closing this.
