### ISSUE TITLE
Automatically enable/disable the Kodi subtitle support option based on what Plex wants

### ISSUE THREAD

**Issue by keithah** [plexinc/plex-for-kodi#18]
Is it possible to do this?

My feature request is for Plex for Kodi to automatically enable or disable the Kodi subtitle setting based on what Plex wants to display. And just for Plex. Restoring/keeping the original value in Kodi.

**Comment by nettosama** [comment]
Yes, enable on the fly this option for the played video, reading from what that particular video has enabled.

**Comment by nettosama** [comment]
Actually, I tried saving this option on the Kodi audio menu displayed by Plex, but everytime I launch the video again, the "Enable subtitle" option appears unchecked.

**Comment by keithah** [comment]
Ok, I see that its a bug and needs to be enabled in both places every time and that 'set as default for all media' isn't even working inside Plex.

**Comment by keithah** [comment]
This appears to be fixed with the next release, which will be .90

**Comment by nettosama** [comment]
Just tested 0.90, and it's working, I get subs automatically after starting the video. thanks!
