### ISSUE TITLE
Seeking backwards not visually represented well

### ISSUE THREAD

**Issue by pannal** [plexinc/plex-for-kodi#181]
Seeking backwards behind the current position doesn't reflect in the timeline visually.

**Comment by ruuk** [comment]
Could you give a more specific example? In my testing just now everything seemed to be working fine when seeking to the left of current, with the progress selection moving, the time indicator updating, and the thumbnails updating.

**Comment by pannal** [comment]
> In my testing just now everything seemed to be working fine when seeking to the left of current, with the progress selection moving, the time indicator updating, and the thumbnails updating.

Using my changes or using the current stable?

**Comment by ruuk** [comment]
The current stable.

**Comment by pannal** [comment]
OK. I might've introduced those problems myself, with the OSD autohide stuff.
