### ISSUE TITLE
"Mark as unwatched"-option not available when item in progress

### ISSUE THREAD

**Issue by pannal** [plexinc/plex-for-kodi#182]
To mimic the behaviour of PlexWeb, the "Mark as unwatched"-option should also be shown for an in-progress item, even though it's not watched yet.

**Comment by ruuk** [comment]
I double checked the behavior in both Roku and web. If an item is unwatched, or watched but in progress, the option should be to 'Mark watched'. The behavior was wrong in the add-on as it ignored whether it was in progress. I just fixed this in c3e56aa53bcd90ef5a6226c6fc74ba03af39e8d5. Are you saying that there is neither option available?

**Comment by pannal** [comment]
IIRC yes, I'm not sure though. I've started watching an episode (for testing my p4k changes), then wanted to remove it from in-progress and reset it again. In PlexWeb I had the option to toggle the watched state to achieve that, in p4k I hadn't.

**Comment by pannal** [comment]
Haven't seen this anymore. Closing.
