### ISSUE TITLE
Show only unwatched, sort by unwatched TV Shows/movies crashes plugin

### ISSUE THREAD

**Issue by Trekster2000** [plexinc/plex-for-kodi#187]
Choosing to show only unwatched shows/movies sorting by unwatched desc crashes the plugin and produces SQLite error on the Plex Server.

- OSMC Vero 4K
- OSMC March update
- Kodi 17.6
- Plex for Kodi 0.1.4
- Plex server 1.13(latest as of today)

Plugin error:

20:41:31.424 T:3326079744 WARNING: CSkinInfo: failed to load skin settings
20:41:32.173 T:3326079744 WARNING: Previous line repeats 2 times.
20:41:32.173 T:3326079744 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-- - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS! Error Type: <class 'plexnet.exceptions.BadRequest'>
Error Contents: (500) internal_server_error
Traceback (most recent call last):
File "/home/osmc/.kodi/addons/script.plex/lib/windows/kodigui.py", line 99, in onInit
self.onFirstInit()
File "/home/osmc/.kodi/addons/script.plex/lib/windows/kodigui.py", line 747, in _onFirstInit
self.onFirstInit()
File "/home/osmc/.kodi/addons/script.plex/lib/windows/library.py", line 480, in onFirstInit
self.fill()
File "/home/osmc/.kodi/addons/script.plex/lib/windows/library.py", line 1227, in fill
self.fillShows()
File "/home/osmc/.kodi/addons/script.plex/lib/windows/busy.py", line 19, in inner
return func(*args, **kwargs)
File "/home/osmc/.kodi/addons/script.plex/lib/windows/library.py", line 1274, in fillShows
jumpList = self.section.jumpList(filter_=self.getFilterOpts(), sort=self.getSortOpts(), unwatched=self.filterUnwatched, type_=type_)
File "/home/osmc/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexlibrary.py", line 182, in jumpList
return plexobjects.listItems(self.server, path, bytag=True)
File "/home/osmc/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexobjects.py", line 516, in listItems
data = data if data is not None else server.query(path)
File "/home/osmc/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexserver.py", line 175, in query
raise exceptions.BadRequest('({0}) {1}'.format(response.status_code, codename))
BadRequest: (500) internal_server_error
-->End of Python script error report<--

Server error:

Apr 30, 2018 20:00:01.387 [0x7fb012111700] ERROR - SQLITE3:0x10, 1, near ",": syntax error
Apr 30, 2018 20:00:01.388 [0x7fb012111700] ERROR - Soci Exception handled: sqlite3_statement_backend::prepare: near ",": syntax error for SQL: select upper(substr((select, 1, 1)) as c,count(distinct metadata_items.id) from metadata_items left join metadata_item_settings on metadata_item_settings.guid=metadata_items.guid and metadata_item_settings.account_id= 1 where metadata_items.library_section_id=? and metadata_items.library_section_id in (4) and ((select count(*) from metadata_items as leaves join metadata_items as parents on leaves.parent_id=parents.id left join metadata_item_settings on metadata_item_settings.guid = leaves.guid and metadata_item_settings.account_id=1 where (parents.parent_id=metadata_items.id or parents.id=metadata_items.id) and (metadata_item_settings.view_count=0 or metadata_item_settings.view_count is null) and leaves.metadata_type in (1, 4, 10))>=1 and metadata_items.metadata_type=2) group by c order by c

**Comment by ruuk** [comment]
@Trekster2000: I can't duplicate this, and at first glance this looks like possibly a server issue. Have you (and if not can you) try the same on a different client and see if there is any weird behavior. The add-on could handle the error better, so on another client you likely wouldn't get a crash on the error but maybe a failure and/or message.

**Comment by pannal** [comment]
I can reproduce this on my Vero with the April update. Only for TV Shows, though, as I don't have the sort-by-unwatched option for Movie libraries.

Rough steps to reproduce (I can't enter my library anymore, so I can't actually filter out the steps properly):
- enter TV library
- filter by UNWATCHED
- sort by Unwatched
- play around with those (I also toggled back and forth between episodes and series view)
- exit the screen
- reenter the screen

Result for me: Blank library screen with no controls.

**Comment by ruuk** [comment]
Thanks @pannal. I was able to duplicate it using your steps, and ultimately reliably reproduce it by:
- Entering the library
- Sort 'By unwatched'
- Filter 'by unwatched'

No issue on Android and I think I see the difference and the reason. Should be a fix coming soon, though I think that SQL error looks fishy, but the add-on is definitely doing something wrong.
