### ISSUE TITLE
Subtitles selection impossible or video parameters completely empty

### ISSUE THREAD

**Issue by adzero** [plexinc/plex-for-kodi#188]
Since 0.1.4 video parameters window doesn't allow to select a subtitle track or appears completely empty. 

[More details](https://forums.plex.tv/discussion/305570/embedded-subtitles-not-displaying-in-plex-for-kodi#latest) on Plex forum

**Comment by pannal** [comment]
I think this can be closed since the latest version, can't it?

**Comment by pannal** [comment]
Closable, as merged to beta

**Comment by adzero** [comment]
Closing issue that is fixed for a while now.
