### ISSUE TITLE
Switching to a Plex Home User will break the plex account link

### ISSUE THREAD

**Issue by d3m0nz** [plexinc/plex-for-kodi#19]
System: Android 5.1.1(FireTV 1st Gen) & Android 7.1.1(Nexus 6P)
Both using Kodi Build 16.1
I have linked kodi with my main Plex account but if any of my plex home users switch to their accounts and exit the addon completely it will need to re-link the addon when you try to launch it again.

**Comment by keithah** [comment]
We need a log.

**Comment by keithah** [comment]
https://forums.plex.tv/discussion/246913/getting-kodi-logs Please provide a log.

**Comment by ruuk** [comment]
Fixed with 8f20f3e30c7dab280ff41508f0a91d59c1187bb7

Please verify with v0.0.89

**Comment by d3m0nz** [comment]
Sorry about the logs thought it uploaded last night. Got off work and tried 0.0.89 and issues is resolved. Thank you
