### ISSUE TITLE
Can't change Audio or Subtitles anymore !

### ISSUE THREAD

**Issue by tug912** [plexinc/plex-for-kodi#190]
I'm using Plex last version in French on Kodi and since a few days i can't change audio or subtitles. 
The menu i used to use is empty.
Any update soon for this bug ?

**Comment by ruuk** [comment]
I'm awaiting feedback on a fix from another report of this issue. If you would like you can test the build below and let me know if it fixes the issue for you.

[script.plex-0.1.6a1.zip](https://github.com/plexinc/plex-for-kodi/files/1989863/script.plex-0.1.6a1.zip)

**Comment by tug912** [comment]
Hi ! Thanks for your quick answer. I tried your new build here and it works now. Bug is corrected, the audio and subtitles box is back ! Thanks. Hope this correction will be added to next update.
Thank you anyway :)

**Comment by ruuk** [comment]
Yeah, I'll be updating with this change, I was just waiting for someone to confirm the fix, so thanks for that.
Closing this as fixed.
