### ISSUE TITLE
Plex-for-kodi does not work well on ios?

### ISSUE THREAD

**Issue by anleebo** [plexinc/plex-for-kodi#207]
Plex-for-kodi does not work well on ios? The screen cannot be touched normally, and the gesture automatically clicks on the screen. The screen is stretched on the ipad.

**Comment by ruuk** [comment]
Kodi is meant primarily for TVs and is not designed as a touch app. The Plex for Kodi app is also not meant to be a touch app, and basically couldn't be even if this was wanted.
