### ISSUE TITLE
Does Plex for Kodi respect the video cache settings in advancedsettings.xml?

### ISSUE THREAD

**Issue by danjames92** [plexinc/plex-for-kodi#245]
Title. 

If not, how do I manually change it?

**Comment by ruuk** [comment]
Yes. The add-on simply gives Kodi the URL to play. So anything to do with playback (i.e. the actual streaming of the audio/video) is handled by Kodi. So it's not really a matter of respecting the setting, the add-on doesn't really have anything to do with it at all :smile:.
