### ISSUE TITLE
24 bit FLAC fails to play

### ISSUE THREAD

**Issue by Zeager0** [plexinc/plex-for-kodi#255]
## Details:
- Add-on version: 0.1.7a2
- Kodi version: 18.0-beta4 git:20181022 - 8af43d2dc5
- OS Platform: Win uwp
- Hardware: Xbox one (original)

I have a kodi logfile with debugging turned on but it includes sensitive information. Can provide snippets if instructed what to look for and a test file if needed.
[mediainfo.txt](https://github.com/plexinc/plex-for-kodi/files/2504686/mediainfo.txt)

**Comment by pannal** [comment]
Without the respective log it'll be hard to debug this (please mask your log and post it). 
Also: Kodi 18 isn't supported right now.
