### ISSUE TITLE
ExtractionError: Can't extract file(s) to egg cache

### ISSUE THREAD

**Issue by halfluck** [plexinc/plex-for-kodi#26]
1. System:  OSX 10.1.1
2. Kodi Version: v17b6 dated 30th November 2016
3. Log File URL:  https://paste.ubuntu.com/23566134/
4. Steps to reproduce
Install Plex for Kodi Plugin and Launch.

  The following error occurred while trying to extract file(s) to the Python egg
                                            cache:
                                            
                                              [Errno 1] Operation not permitted: '/private/var/mobile/Containers/Data/Application/E5153FBB-5D53-4AC8-9B33-B2A7B220A598/.python-eggs'
                                            
                                            The Python egg cache directory is currently set to:
                                            
                                              /private/var/mobile/Containers/Data/Application/E5153FBB-5D53-4AC8-9B33-B2A7B220A598/.python-eggs
                                            
                                            Perhaps your account does not have write access to this directory?  You can
                                            change the cache directory by setting the PYTHON_EGG_CACHE environment
                                            variable to point to an accessible directory.

**Comment by keithah** [comment]
You said OS X, but this is obviously iOS and looks like it could be a sandboxing issue related to side loading the app? Can you try to create the .python-eggs folder in the path above?

**Comment by halfluck** [comment]
Hello Keithhah,

Yes my bad, Definitely iOS.
Yes its just a signed .deb install of Kodi on an iPad (not jailbroken)
I can browse anywhere in /Documents/Kodi/ (system/userdata/addons/temp etc) 
How would i go about changing the PYTHON_EGG_CACHE environment variable?

Thanks Rob.

**Comment by keithah** [comment]
This is not add-on related. Post to Kodi forums for questions like this. Closing this ticket.
