### ISSUE TITLE
script.plex: ERROR on 

### ISSUE THREAD

**Issue by dawesc** [plexinc/plex-for-kodi#261]
## Description:
Getting this warning on plex startup, seems to have no operational effect:
<pre>
20:38:28.332 T:3513885552   ERROR: _________________________________________________________________________________
20:38:28.333 T:3513885552   ERROR: script.plex: ERROR:
20:38:28.333 T:3513885552   ERROR:     Traceback (most recent call last):
20:38:28.333 T:3513885552   ERROR:       File "/storage/.kodi/addons/script.plex/lib/backgroundthread.py", line 83, in _runTask
20:38:28.333 T:3513885552   ERROR:         task._run()
20:38:28.333 T:3513885552   ERROR:       File "/storage/.kodi/addons/script.plex/lib/backgroundthread.py", line 37, in _run
20:38:28.333 T:3513885552   ERROR:         self.run()
20:38:28.333 T:3513885552   ERROR:       File "/storage/.kodi/addons/script.plex/lib/windows/home.py", line 68, in run
20:38:28.333 T:3513885552   ERROR:         hubs = HubsList(plexapp.SERVERMANAGER.selectedServer.hubs(self.section.key, count=HUB_PAGE_SIZE)).init()
20:38:28.333 T:3513885552   ERROR:       File "/storage/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexserver.py", line 141, in hubs
20:38:28.333 T:3513885552   ERROR:         data = self.query(q, params=params)
20:38:28.333 T:3513885552   ERROR:       File "/storage/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexserver.py", line 193, in query
20:38:28.333 T:3513885552   ERROR:         return ElementTree.fromstring(data) if data else None
20:38:28.333 T:3513885552   ERROR:       File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
20:38:28.333 T:3513885552   ERROR:       File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
20:38:28.333 T:3513885552   ERROR:       File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
20:38:28.333 T:3513885552   ERROR:     ParseError: duplicate attribute: line 403, column 873
</pre>

## Details:
- Add-on version:
repo master and develop @ 1.7.a2 @ adcb590422d43ce7ae5a064bf197fdda0c1768dc
- Kodi version:
kodi-18.0rc1-Leia
- OS Platform:
LibreElec Master @49049575d7e1c7743dea3a3e55d7b6e4ae56c91e
- Hardware:
S905 (MXQ)

## Checklist
- [x] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue; pasted above
- [ ] I have added appropriate GitHub labels

**Comment by ruuk** [comment]
What's the Plex server version?

**Comment by gbooker** [comment]
FWIW, this was a server bug producing invalid XML that was fixed in 1.14.0.  Closing this issue as the bug was fixed there.
