### ISSUE TITLE
Clock appears over the search menu on left hand side

### ISSUE THREAD

**Issue by Plugitt** [plexinc/plex-for-kodi#31]
The clock on the home screen appears over the search menu on the top left hand side of the screen, when it should be located on the top right hand side.

**Comment by keithah** [comment]
![image](https://cloud.githubusercontent.com/assets/684920/20862497/33c44bf0-b961-11e6-968f-f9530d5fa59c.png)

Doesn't for me. What skin are you using? Please attach screenshot + log.

**Comment by Plugitt** [comment]
Thanks for getting back to me, I am using a skin called Hyper TT, I believe it is based on the Aeon Nox skin. Please find attached both the kodi.log and a screenshot of said issue.
[kodi.log.zip](https://github.com/plexinc/plex-for-kodi/files/629167/kodi.log.zip)


![screen](https://cloud.githubusercontent.com/assets/24359188/20862589/da05f4e2-b9a6-11e6-863e-2a994b55d98c.png)

**Comment by keithah** [comment]
We aren't supporting any skins but the default ones (Confluence and Estuary) currently. We look look into supporting other skins in the repo once we're feature complete.
