### ISSUE TITLE
[Feature Request] Add Plex's "Skip Intro"

### ISSUE THREAD

**Issue by requiem240sx** [plexinc/plex-for-kodi#316]
Plex server now has a cool new feature to "Skip Intros" on tv shows.  It doesn't appear to have the "Skip Intro" pop up in Kodi though after the latest Plex [Update](https://support.plex.tv/articles/skip-content/). 

I use an Odroid N2 running CorELEC with Kodi v18 "Leia", with the official Plex for kodi add on.  My mobile app and browser both have "Skip Intro" popping up fine, so I know its setup correctly server side, however I'm not seeing it on my Kodi devices.  Just wondering if I can submit a feature request for this, and/or if someone knows a way to get this working... maybe i'm doing something wrong.

Huge shoutout to everyone pushing changes on this! I love and use it faithfully every day!

**Comment by ruuk** [comment]
There's already a PR open for this (#314), that should be merged soon.
