### ISSUE TITLE
Dialog when 'my.plexapp.com' is not reachable

### ISSUE THREAD

**Issue by keithah** [plexinc/plex-for-kodi#32]
Should have some sort of dialog when you can't reach my.plexapp.com, instead of crashing currently.

ref: https://forums.plex.tv/discussion/247601/plex-add-on-for-kodi-crashes-at-sign-in#latest

**Comment by keithah** [comment]
Dialog is presented, so closing out.

**Comment by keithah** [comment]
Can we update it to say "Can't connect to plex.tv” / “Check your internet connection and try again."

**Comment by ruuk** [comment]
Changed for next version :)
