### ISSUE TITLE
Collection for kodi :(

### ISSUE THREAD

**Issue by kevin91270** [plexinc/plex-for-kodi#339]
## Description:
can you add collection like this on plex-for-kodi, you have add it on plex media player and plex.tv, ithink it is an easy update and make it so nicer 👍 

![image](https://user-images.githubusercontent.com/40793654/98727064-a3cbac00-2397-11eb-84bb-23c3d28de22e.png)

## Details:
- Add-on version:latest
- Kodi version:latest stable
- OS Platform:
- Hardware:

## Checklist
- [ ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [x] I have added appropriate GitHub labels

**Comment by ruuk** [comment]
Added.

**Comment by kevin91270** [comment]
Where ?

**Comment by ruuk** [comment]
The code for the change has been added. It'll be in the next update.

**Comment by kevin91270** [comment]
> The code for the change has been added. It'll be in the next update.

dou you when this update is comming ?
