### ISSUE TITLE
Video takes long time to start

### ISSUE THREAD

**Issue by Generator** [plexinc/plex-for-kodi#347]
## Description:
After upgrading Kodi to v19, Plex for Kodi addon takes a long time to start any video (almost 1 minute), and shows the warning "Source Too Slow For Continuous Playback".  

PS: Issue wasn't present on previews on previews version. The device is about 1m over WiFi, no other connection issues.

EDIT: Also pausing and resuming or change subtitles causes the video to fail.

## Details:
- Add-on version: v0.3.3
- Kodi version: 19.0.0
- OS Platform: Android 
- Hardware: X96 Max+ (Android TV Box)

## Checklist
- [x] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

Logfile: 
[kodi.log](https://github.com/plexinc/plex-for-kodi/files/6055653/kodi.log)

**Comment by Ryushin** [comment]
I have the same problem happening on my Sony 900E TV that it takes about a minute to start a video.  But it crashes the 2019 Shield to the point that I have to adb reboot the Shield or power it on and off to have it work again as the remote stops working.   I have a "adb logcat | grep -i kodi" if that will be helpful.

**Comment by Generator** [comment]
@Ryushin you can enable "Enable debug logging" and send the kodi.log located on "Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log"  
https://kodi.wiki/view/Log_file/Easy

**Comment by PowershellBacon** [comment]
I have this on both my Shield tv's. New v19 kodi updated and plex updated, Now ALL videos take forever to try and load, 4k content no longer loads. Before in v18 with plex addon, all content plays instantly with no buffering and no transcoding. I had to roll back to kodi18 manually and install plex for kodi again and then it all works normally.  

What I see on the plex side with v19/plex is it pegs the server for data (around 500Mbps) for 10-15 seconds then the app crashes on the shield. Some content will eventually play, ie 1080p content or small files.

**Comment by Generator** [comment]
Was this fixed by some dependency?
I've watch two videos without the issue, didn't notice if there was some dependency update or not, but looks like the issue is gone.

**Comment by PowershellBacon** [comment]
Have you tested hvec content? like some 4k content?

**Comment by ruuk** [comment]
From the logs I've seen it looks like the app is failing to load settings so it's falling back  to defaults. This means anything affected by settings might be transcoded when it might have been direct played previously, which depending on the server and media could definitely account for the slow start.

There's a new settings format for add-ons that as far as I know is still optional, but perhaps that's not the case, or maybe there's a bug in Kodi.

In any case I plan to see about fixing the issue soon.

**Comment by Generator** [comment]
@PowershellBacon tested with 4K, still with the issue

**Comment by ruuk** [comment]
Hmm... @Generator, are you also using Android? I just tested (Linux) and don't have the issue.

**Comment by ruuk** [comment]
Looking closer at the logs, it looks like my original thinking was wrong. The item playing in the logs is direct playing, so it's not a transcode that is causing the slowdown. I think I can see where it takes a minute from where the add-on asks the Kodi player to play and playback actually starts. I'm starting to think this might be an Android specific issue (or at least a Kodi issue) because the delay is not happening in the add-on. The add-on gives the URL to the Kodi player and starts playback, and a minute later playback actually starts.

**Comment by Ryushin** [comment]
Tried some more testing on the 2019 Shield.  If I disable HEVC in video settings I can playback with transcoding.  If I enable HEVC and try playing back HD or 4K HEVC it hangs the Shield and I have to adb reboot or physically power cycle it.  I tired disabling audio passthrough and (TrueHD passthrough has issues in Kodi19) and the results were the same.

**Comment by Generator** [comment]
@ruuk tried with Archlinux but i'm having other issues with Kodi 19 not related to plugin, can't fetch adddons  mirrors

@Ryushin tried with HEVC/H265,H264 both with sane issue

**Comment by vangeliis** [comment]
Hey,

Same issue here with KODI 19, Plex Add-on 0.3.3 on ShieldTV 2017. Video playback doesn't start and eventually KODI crashes. This is so frustrating since KODI 18 with PLEX add-on worked flawlessly for me. How do I downgrade?

Many thanks.

**Comment by mirkster** [comment]
I have the same issue with Kodi 19 (Coreelec) and Plex for Kodi 0.3.3 running on an Odroid N2. In my case it takes about 15 seconds for videos to start and I get the message "Source Too Slow For Continuous Playback" but they do play. The server is on a Synology DS918+. Never had any issues before on Kodi 18, used to have instant play with no error messages.

**Comment by vangeliis** [comment]
Any news on this issue? Thanks.

**Comment by Desef** [comment]
I have the same problem, with an Android 9 TV box and my android 10 phone. It takes between 1 and 2 minutes for a video to start playing.

Had there been any progress with stressing this issue?

**Comment by FredericMa** [comment]
I'm experiencing the same issue after upgrading to Kodi 19.
I'm running Kodi via LibreELEC on a Raspberry Pi 4.

**Comment by Desef** [comment]
I deleted V19.1 and installed version 18.9 and the latest Plex add-on this morning. My system is now working fine.

**Comment by vangeliis** [comment]
> Hey,
> 
> Same issue here with KODI 19, Plex Add-on 0.3.3 on ShieldTV 2017. Video playback doesn't start and eventually KODI crashes. This is so frustrating since KODI 18.9 with PLEX add-on worked flawlessly for me. How do I downgrade?
> 
> Many thanks.
> 
> Edit:
> I was able to downgrade to KODI 18.9
> Copied https://mirrors.kodi.tv/releases/android/arm64-v8a/kodi-18.9-Leia-arm64-v8a.apk to a pendrive
> Installed X-plore File Manager on the ShieldTV https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore&hl=en_GB&gl=US
> Allowed X-plore to install apps
> Pointed X-plore to the apk on the pendrive and installed KODI 18.9 and then Plex for Kodi 0.2.3
> 
> Now video playback works great again 😊

Possible SOLUTION: 
https://forums.plex.tv/t/testers-needed-plex-for-kodi-kodi-19-compatibility/481208/172

**Comment by mirkster** [comment]
Wow this actually worked for me. What did the trick was in the server settings just removing the IP range I had previously put in the field "List of IP addresses and networks that are allowed without auth". It didn't work right away but once I restarted the client it all started working perfectly.

Thank you very much for posting this!

**Comment by mirkster** [comment]
> > Hey,
> > Same issue here with KODI 19, Plex Add-on 0.3.3 on ShieldTV 2017. Video playback doesn't start and eventually KODI crashes. This is so frustrating since KODI 18.9 with PLEX add-on worked flawlessly for me. How do I downgrade?
> > Many thanks.
> > Edit:
> > I was able to downgrade to KODI 18.9
> > Copied https://mirrors.kodi.tv/releases/android/arm64-v8a/kodi-18.9-Leia-arm64-v8a.apk to a pendrive
> > Installed X-plore File Manager on the ShieldTV https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore&hl=en_GB&gl=US
> > Allowed X-plore to install apps
> > Pointed X-plore to the apk on the pendrive and installed KODI 18.9 and then Plex for Kodi 0.2.3
> > Now video playback works great again 😊
> 
> Possible SOLUTION:
> https://forums.plex.tv/t/testers-needed-plex-for-kodi-kodi-19-compatibility/481208/172

Wow this actually worked for me. What did the trick was in the server settings just removing the IP range I had previously put in the field "List of IP addresses and networks that are allowed without auth". It didn't work right away but once I restarted the client it all started working perfectly.

Thank you very much for posting this!

**Comment by vangeliis** [comment]
> > > Hey,
> > > Same issue here with KODI 19, Plex Add-on 0.3.3 on ShieldTV 2017. Video playback doesn't start and eventually KODI crashes. This is so frustrating since KODI 18.9 with PLEX add-on worked flawlessly for me. How do I downgrade?
> > > Many thanks.
> > > Edit:
> > > I was able to downgrade to KODI 18.9
> > > Copied https://mirrors.kodi.tv/releases/android/arm64-v8a/kodi-18.9-Leia-arm64-v8a.apk to a pendrive
> > > Installed X-plore File Manager on the ShieldTV https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore&hl=en_GB&gl=US
> > > Allowed X-plore to install apps
> > > Pointed X-plore to the apk on the pendrive and installed KODI 18.9 and then Plex for Kodi 0.2.3
> > > Now video playback works great again 😊
> > 
> > 
> > Possible SOLUTION:
> > https://forums.plex.tv/t/testers-needed-plex-for-kodi-kodi-19-compatibility/481208/172
> 
> Wow this actually worked for me. What did the trick was in the server settings just removing the IP range I had previously put in the field "List of IP addresses and networks that are allowed without auth". It didn't work right away but once I restarted the client it all started working perfectly.
> 
> Thank you very much for posting this!

All credit goes to https://forums.plex.tv/u/macieksoft for discovering the workaround. Hoping this gets fixed soon so we can disable authentication for local devices once again.

**Comment by mfraser** [comment]
The only issue with removing the IP range is that if your internet connection is down, you won't be able to play anything.

**Comment by Generator** [comment]
@mfraser you can connect over DLNA as workaround til fixed.

**Comment by ruuk** [comment]
Fixed in #358 an submitted to official Kodi repo.
