### ISSUE TITLE
Python 3.9 breaks threading

### ISSUE THREAD

**Issue by mliudev** [plexinc/plex-for-kodi#349]
## Description:

I'm getting this error:

```
File "/var/lib/kodi/.kodi/addons/script.plex/lib/backgroundthread.py", line 129, in shutdown
    if self._thread and self._thread.isAlive():
AttributeError: 'KillableThread' object has no attribute 'isAlive'.
```

When using the plex for kodi addon. According to: https://github.com/plexinc/plex-for-kodi...ils.py#L32 a `KillableThread` inherits from `threading.Thread` which in python 3.9 does not have an `isAlive()` attribute. Instead it should be `is_alive()`.

## Details:
- Add-on version: 0.3.3
- Kodi version: 19.0-9
- OS Platform: Arch Linux
- Hardware:

i7-4790K
Radeon RX570

Cross posted here: https://forum.kodi.tv/showthread.php?tid=361214

## Checklist
- [x] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

**Comment by dmarkey** [comment]
Add on is pretty broken because of this for me.

**Comment by mliudev** [comment]
@dmarkey I've fixed this for myself by just updating all the calls that were deprecated. I've created a PR for it as well linked above. This might work for you if you know how to replace the addon with the one in my branch.

**Comment by THGhost** [comment]
It's 100% broken right now. Opening a movie/episode completely locks the add-on, preventing you from moving up/down/left/right. You can't play the movie/episode, enable subs, anything. All you can do is go back.

**Comment by mliudev** [comment]
Closing this as I no longer use plex for kodi.

**Comment by ruuk** [comment]
Fixed via https://github.com/plexinc/plex-for-kodi/commit/984a572248fe5c1af7451dc3d36a3e7bd82c6dd9 (thanks to @mliudev)
