### ISSUE TITLE
Playlist view loads whole list at once (slow for big playlists)

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-for-kodi#35]
It takes a minute or two to load a big playlist.

Ought to maybe load them progressively for smoothness.

Also can't interact with the playlist until it finishes loading.

**Comment by keithah** [comment]
@Enigma0 this issue should be resolved, they load progressively now. I'm closing this out, but if you still have an issue feel free to comment and reopen it. Thanks for reporting!

**Comment by Enigma0** [comment]
@keithah  Nope - working great - thanks.

As a general enhancement, it would be nice to have the images/details fade in. Currently they pop and that is across the board - anywhere in the Plex addon.
