### ISSUE TITLE
Autostart Plex after running Kodi

### ISSUE THREAD

**Issue by subdesign** [plexinc/plex-for-kodi#355]
Back to 2018 when I bought my Qnap nas I successfully setup the system that after Kodi (18.5) runs the Plex addon starts automatically. Really I can't remember what was the trick.
Now, I installed Kodi 19, and latest Plex addon 0.3.3 but I can't figure out how to force Plex to autostart without user interaction. Is it possible from Kodi or need some scripting for this (https://kodi.wiki/view/Autoexec_Service) ?

Thanks

- Add-on version: 0.3.3
- Kodi version: 19.1
- OS Platform: Qnap's own Linux
- Hardware: Qnap TS 251+

**Comment by Generator** [comment]
Go to Settings (on your account name), and you have the option there.

**Comment by subdesign** [comment]
I don't have that option on the Qnap build. 
But finally I figured out with the above mentioned info, created an autoexec service which starts automatically the plex service. I'm happy with that solution.
