### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by erolmutlu** [plexinc/plex-for-kodi#36]
19:47:19 T:139658994968320   ERROR: script.plex: ERROR:
19:47:19 T:139658994968320   ERROR:     Traceback (most recent call last):
19:47:19 T:139658994968320   ERROR:       File "/home/erol/.kodi/addons/script.plex/lib/main.py", line 60, in _main
19:47:19 T:139658994968320   ERROR:         if plex.init():
19:47:19 T:139658994968320   ERROR:       File "/home/erol/.kodi/addons/script.plex/lib/plex.py", line 240, in init
19:47:19 T:139658994968320   ERROR:         token = authorize()
19:47:19 T:139658994968320   ERROR:       File "/home/erol/.kodi/addons/script.plex/lib/plex.py", line 300, in authorize
19:47:19 T:139658994968320   ERROR:         pinLoginWindow.setPin(pl.pin)
19:47:19 T:139658994968320   ERROR:       File "/home/erol/.kodi/addons/script.plex/lib/windows/signin.py", line 94, in setPin
19:47:19 T:139658994968320   ERROR:         pinImage = image.textToImage(' '.join(list(pin)))
19:47:19 T:139658994968320   ERROR:       File "/home/erol/.kodi/addons/script.plex/lib/image.py", line 54, in textToImage
19:47:19 T:139658994968320   ERROR:         usr_font = ImageFont.truetype(fontPath, size)
19:47:19 T:139658994968320   ERROR:       File "/usr/lib64/python2.7/site-packages/PIL/ImageFont.py", line 239, in truetype
19:47:19 T:139658994968320   ERROR:         return FreeTypeFont(font, size, index, encoding)
19:47:19 T:139658994968320   ERROR:       File "/usr/lib64/python2.7/site-packages/PIL/ImageFont.py", line 128, in __init__
19:47:19 T:139658994968320   ERROR:         self.font = core.getfont(font, size, index, encoding)
19:47:19 T:139658994968320   ERROR:       File "/usr/lib64/python2.7/site-packages/PIL/ImageFont.py", line 37, in __getattr__
19:47:19 T:139658994968320   ERROR:         raise ImportError("The _imagingft C module is not installed")
19:47:19 T:139658994968320   ERROR:     ImportError: The _imagingft C module is not installed
19:47:19 T:139658994968320   ERROR: _________________________________________________________________________________
19:47:19 T:139658994968320   ERROR: `
19:47:19 T:139658994968320  NOTICE: script.plex: SHUTTING DOWN...
19:47:19 T:139658994968320  NOTICE: script.plex: Checking for any remaining threads
19:47:19 T:139658994968320  NOTICE: script.plex: Waiting on: PLAYER:MONITOR...
19:47:19 T:139660149696640   ERROR: Unable to load libgif.so.4, reason: libgif.so.4: cannot open shared object file: No such file or directory
19:47:19 T:139660149696640   ERROR: Gif::Gif(): Could not load giflib
19:47:19 T:139658369033984  NOTICE: script.plex: Player: Closed
19:47:19 T:139658360641280  NOTICE: script.plex: Cron stopped
19:47:19 T:139658994968320  NOTICE: script.plex: FINISHED
19:47:19 T:139658360641280 WARNING: CreateLoader - unsupported protocol(script) in script://script.plex/-poster.jpg
19:47:19 T:139658360641280 WARNING: CreateLoader - unsupported protocol(script) in script://script.plex/-poster.png
19:47:19 T:139658360641280 WARNING: CreateLoader - unsupported protocol(script) in script://script.plex/-banner.jpg
19:47:19 T:139658360641280 WARNING: CreateLoader - unsupported protocol(script) in script://script.plex/-banner.png
19:47:57 T:139658369033984 WARNING: CreateLoader - unsupported protocol(script) in script://script.plex/-poster.jpg
19:47:57 T:139658369033984 WARNING: CreateLoader - unsupported protocol(script) in script://script.plex/-poster.png
19:47:57 T:139658369033984 WARNING: CreateLoader - unsupported protocol(script) in script://script.plex/-banner.jpg
19:47:57 T:139658369033984 WARNING: CreateLoader - unsupported protocol(script) in script://script.plex/-banner.png

############ END Kodi CRASH LOG #############

**Comment by ruuk** [comment]
[script.plex-0.0.94a1.zip](https://github.com/plexinc/plex-for-kodi/files/637382/script.plex-0.0.94a1.zip)

Try this version, and let me know if it fixes the issue.

**Comment by keithah** [comment]
Duplicate issue #39 , closing, thanks for reporting.
