### ISSUE TITLE
A lot of errors "AttributeError: 'Thread' object has no attribute 'isAlive'"

### ISSUE THREAD

**Issue by CHeGIVaRO** [plexinc/plex-for-kodi#374]
## Details:
- Add-on version: 0.3.4
- Kodi version: 19.4
- OS Platform: Batocera Linux
- Hardware: raspberry pi 4
python 3.10

Video is not playing. The isAlive function has been renamed to is_alive. I renamed it in all files and everything worked, please fix this error.

**Comment by horschdel** [comment]
I would like to second this.

**Comment by viyh** [comment]
Also getting this. Same as details as OP except Raspberry Pi OS.

**Comment by ruuk** [comment]
Submitted an update to the Kodi repo which should fix this: https://github.com/xbmc/repo-scripts/pull/2358
