### ISSUE TITLE
Typo in Delete dialog box

### ISSUE THREAD

**Issue by keithah** [plexinc/plex-for-kodi#41]
All 4 dialogs say 'Really Delete?'

**Comment by ruuk** [comment]
What's the typo?

**Comment by keithah** [comment]
All 4 dialogs say 'Really Delete?' instead of at least one box saying 'Cancel'.

**Comment by ruuk** [comment]
You click delete from the dropdown.

The dialog says:

Heading: Really delete?
Message: Are you sure you really want to delete this media?

And there is a yes button and a no button.

Click yes and it deletes. Click no and it doesn't.

I'm still not getting what you're saying :)
