### ISSUE TITLE
Search function finds playlists that are not present in a users managed content

### ISSUE THREAD

**Issue by keithah** [plexinc/plex-for-kodi#42]
When initiating a Search the playlists presented for said search presents Playlists that are not in a users managed content. It denotes playlists from userA user section that should not be presented in UserB user section. When entering the Playlist that should not be present said playlists movies are empty.

ref: https://forums.plex.tv/discussion/248342/bug-search-function-finds-playlists-that-are-not-present-in-a-users-managed-content#latest

**Comment by ruuk** [comment]
This appears to be a server side issue. Added a workaround that displays a message dialog when selecting a playlist the user can't access.

**Comment by elan** [comment]
It's been fixed on the server side, should make it into release before long.

**Comment by ruuk** [comment]
Awesome :)

**Comment by keithah** [comment]
I removed the bug tag, but don't want to close so we remember to remove the dialog once the fix is released, so reclassified it to 'missing feature' now.

**Comment by keithah** [comment]
Looks like PMS 1.3.3 has this fix in it.

**Comment by elan** [comment]
Yep!
