### ISSUE TITLE
Blacks screen on play when refreshrate switching is enabled

### ISSUE THREAD

**Issue by ptr727** [plexinc/plex-for-kodi#56]
Running LibreELEC Generic 7.0.2 on Intel NUC D34010WYK Core i3.
Connected to Marantz AVR via HDMI, connected to LG TV.
LibreELEC configured for HDMI audio passthrough, and refresh rate switching on start/stop.
Running Plex Plugin v0.0.99.

The movies plays fine using Kodi, DTS-HD passthrough, 24fps.

When starting a movie in the Plex plugin, the screen will go black with no audio.
Pressing the stop or back remote buttons normally returns to the Plex screen.

If I disable refresh rate switching, the video plays at 1080p 60fps in Plex.
If I enable refresh rate switching, but add a 2s pause, the video also plays in Plex.

But, whenever the video is stopped in Plex, and the screen goes from 24p to 60p, the screen stays black, and no amount of keypresses gets it back again, a reboot is required.

Logs attached, not with debug logging enabled, not possible right now, sorry, kids are using the system.

[log-2016-12-27-00.51.04.zip](https://github.com/plexinc/plex-for-kodi/files/673431/log-2016-12-27-00.51.04.zip)

**Comment by keithah** [comment]
we need debug logging to see anything. I'm also curious if Kodi v17 has the same issue:
https://libreelec.tv/2016/12/libreelec-krypton-v7-90-010-alpha/

If it doesn't, I'd appreciate v17 logs with debugging enabled.

**Comment by ptr727** [comment]
Also happens with latest Alpha LibreELEC 7.90.010.
Same behavior, start play refresh rate switch black screen.

Debug enabled logs attached.

[log-2016-12-27-17.17.29.zip](https://github.com/plexinc/plex-for-kodi/files/674436/log-2016-12-27-17.17.29.zip)

**Comment by ptr727** [comment]
Last night I found a video where playing direct from Kodi also produces a black screen, so this may be a LibreELEC or Kodi issue, and not a plugin issue?

I logged the issue here:
https://forum.libreelec.tv/thread-3358.html

**Comment by keithah** [comment]
Thanks for reporting, but unfortunately, it does seem Kodi/LibreELEC related and posting it there is probably your best bet. If you don't get any responses over at LE forums in a few days ping me again and I'll reach out to one of the Kodi devs who worked on intel stuff and see if he has any clues.

**Comment by ptr727** [comment]
Thanks, per Milhouse it may be an Intel upstream issue, but no word from any "Intel Experts" on how to proceed, per forum threads I'm not alone with this issue:
http://forum.kodi.tv/showthread.php?tid=298462&pid=2490151#pid2490151

I don't want to just log yet another bug with freedesktop, I'd like somebody with a vested interest in Kodi and LE to get this issue resolved.

**Comment by keithah** [comment]
So the guy I was going to ping is responding in that thread, and hasn't said anything about your issue, so he definitely saw it and doesn't have anything to say. :\ unfortunately, I'll be closing this ticket out, since its unrelated to the add-on itself, but I hope it gets figured out on the LE/Kodi side!
