### ISSUE TITLE
Not being able to log into a Home user

### ISSUE THREAD

**Issue by keithah** [plexinc/plex-for-kodi#61]
log: http://paste.ubuntu.com/23709068/

Using .100a4, at the Home user selection screen, unable to select a user. Log shows a python exception.

ref: https://forums.plex.tv/discussion/comment/1334849/#Comment_1334849

**Comment by Skaronator** [comment]
Has been fixed here: https://github.com/plexinc/plex-for-kodi/issues/63#issuecomment-272019091

**Comment by keithah** [comment]
@Skaronator can you verify .100a7 fixes the home issue for you?
https://forums.plex.tv/discussion/comment/1333079/#Comment_1333079

**Comment by Skaronator** [comment]
It doesn't find my server? It's the same issue I've described [here](https://github.com/plexinc/plex-for-kodi/issues/63#issuecomment-272011594) and has been fixed in [this](https://github.com/plexinc/plex-for-kodi/issues/63#issuecomment-272019091) private build.

**Comment by ruuk** [comment]
@Skaronator: Actually the private build I sent you is basically an 0.0.99 build with some some early fixes for 0.0.100. The changes that caused the 'cannot find my server' issue for you are in later builds. I sent you the earlier build so we could verify your original issue fixed without first having to get past the new issue.
If .100a7 still has the 'cannot find my server' issue for you, then we don't want to release until we fix that.

**Comment by keithah** [comment]
Can we get a log of the 'cannot find my server' issue you're experiencing?

**Comment by Skaronator** [comment]
@ruuk: Alright, pretty hard to track from outside what's going on. I really don't like the private development at all and it would deter many developers to contribute. I think you underestimated the open source community.

Anyway @keithah here you go: [kodi.zip](https://github.com/plexinc/plex-for-kodi/files/704188/kodi.zip)

**Comment by keithah** [comment]
we're are trying to be as open source as possible, while respecting all the parties involved. The hope is to the private and public branches to be synced as much as possible, so the community can help.

**Comment by keithah** [comment]
[script.plex-0.0.100a8.zip](https://github.com/plexinc/plex-for-kodi/files/706231/script.plex-0.0.100a8.zip)

@Skaronator can you test this release and see if it fixes your issue?

**Comment by Skaronator** [comment]
Hum not it doesn't even log me in in my plex account?

![image](https://cloud.githubusercontent.com/assets/2886913/21958220/99260006-daa9-11e6-88e6-385b21d4ec39.png)
[kodi.zip](https://github.com/plexinc/plex-for-kodi/files/706236/kodi.zip)

**Comment by ruuk** [comment]
Thanks @Skaronator for the continued testing and logs, I really appreciate it. I think I have an idea of what might be the problem.

**Comment by ruuk** [comment]
@Skaronator 

This should be the last time I bug you :) I was able to duplicate the issue you were having with the latest builds and fixed it. It was windows specific and all windows users would have had the same issue.

If you could test the version in the post linked below I would really appreciate it.

[Forum Post (0.0.100a12)](https://forums.plex.tv/discussion/comment/1348434/#Comment_1348434)

Thanks!

**Comment by Skaronator** [comment]
Everything seems working, awesome!

Just one thing: would be good if it's preload the next image in the photo viewer or even better if you add a setting with default 3 images. (3 images pre and post of current viewed image)

**Comment by keithah** [comment]
Setting creep is something Plex tries to avoid heavily, so I doubt that'll be something we could push for. Preloading the next image in the photo viewer though is a good feature add (and if someone PR'd it, might get in) but since other clients don't do that, unfortunately we're re-implementing that design currently. It's something that Plex should definitely do across the board though. Appreciate your testing and feedback and glad we finally got a new working build!
