### ISSUE TITLE
picture album not loading

### ISSUE THREAD

**Issue by Skaronator** [plexinc/plex-for-kodi#63]
If you go to your photo libary and click on any album it is loading nothing.

It looks like this:
![kodi_2017_01_07_13_44_11_014](https://cloud.githubusercontent.com/assets/2886913/21741731/9fc5685e-d4df-11e6-943e-bd200ce23376.png)

And the log is thowing this:
```
13:44:08.325 T:20192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.KeyError'>
Error Contents: ('photodirectory',)
Traceback (most recent call last):
File "C:\Users\Skaronator\AppData\Roaming\Kodi\addons\script.plex\lib\windows\kodigui.py", line 99, in onInit
self.onFirstInit()
File "C:\Users\Skaronator\AppData\Roaming\Kodi\addons\script.plex\lib\windows\kodigui.py", line 699, in _onFirstInit
self.onFirstInit()
File "C:\Users\Skaronator\AppData\Roaming\Kodi\addons\script.plex\lib\windows\library.py", line 250, in onFirstInit
self.setProperty('sort.display', SORT_KEYS[self.section.TYPE].get(self.sort, SORT_KEYS['movie'].get(self.sort))['title'])
KeyError: ('photodirectory',)
-->End of Python script error report<--

```

Tested on Kodi 16.1 on Android TV and on Kodi 17 rc2 on Windows 10. (Log from W10)

**Comment by keithah** [comment]
We need a full log.
https://forums.plex.tv/discussion/246913/getting-kodi-logs#latest

**Comment by Skaronator** [comment]
Here is the full log. You'll see the same at Line ~1249.
[kodi.zip](https://github.com/plexinc/plex-for-kodi/files/692380/kodi.zip)


I'm not at home so tried to reproduce it via remote access on another PC and have the same result.

**Comment by keithah** [comment]
Can you try:
https://forums.plex.tv/discussion/251413/only-for-serious-testers-bleeding-edge-testing-releases/

.100a5 located in this thread? It may fix your issue. If not we need another log with the .100a5 release. Thanks!

**Comment by Skaronator** [comment]
I'm supposed to uninstall the old version?

If not:
The fast user switching UI isn't loading at all, so cannot select my Account.

Its looking like this without the "box" in the middle (it pop up when I press F11 for the screenshot)
![kodi_2017_01_11_19_11_13_319](https://cloud.githubusercontent.com/assets/2886913/21860704/1cabcee4-d832-11e6-9b92-e66314c1f208.png)

[kodi.zip](https://github.com/plexinc/plex-for-kodi/files/699698/kodi.zip)

**Comment by ruuk** [comment]
Thanks for the log and screenshot, it's much appreciated :)

Could you give this version a try?

[script.plex-0.0.100a6.zip](https://github.com/plexinc/plex-for-kodi/files/700184/script.plex-0.0.100a6.zip)

**Comment by Skaronator** [comment]
Now it won't connect to my server anymore. (I'm still not at home, so remote connection) Weninterface (app.plex.tv) also works fine.

![kodi_2017_01_11_23_07_37_999](https://cloud.githubusercontent.com/assets/2886913/21868458/11e5316e-d853-11e6-9158-ea0401303704.png)

Log: 
[kodi.zip](https://github.com/plexinc/plex-for-kodi/files/700207/kodi.zip)

**Comment by Skaronator** [comment]
Switched back to 0.0.99 and everything works again, so its not a connection issue.

**Comment by ruuk** [comment]
Again, thanks for the logs and screenshots. I'm basically positive your original issue is fixed in the latest code that's in the testing versions. The problem is that your hitting another issue some users are having with these builds where the request times out before it connects to the Plex servers.

Rather than make you try to first get past a different issue than the one you were reporting, here is an earlier build that should fix the issue.

[plex-for-kodi-private-develop.zip](https://github.com/plexinc/plex-for-kodi/files/700281/plex-for-kodi-private-develop.zip)

**Comment by Skaronator** [comment]
Everything seems working now, thanks!

One little thing I've noticed: If you start a diashow it'll switch to the next image before the current image is loaded. So a waitUntil image loaded would be good before it start the countdown for switch.
