### ISSUE TITLE
multi part movies won't playback

### ISSUE THREAD

**Issue by keithah** [plexinc/plex-for-kodi#64]
log: http://paste.ubuntu.com/23757104/

Cannot play multipart movies with naming convention correctly applied (cd1, cd2 or part1, part2..).

ref: https://forums.plex.tv/discussion/253095/bug-cannot-play-multipart-movies#latest

**Comment by ruuk** [comment]
Will now play, but only the first part (though playing again with resume will play the subsequent part). Work still needs to be done to handle these correctly.
