### ISSUE TITLE
Playlists stop playing after a time

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-for-kodi#66]
Is this intended? It stops playing and I have to go back and re-shuffle the list occasionally.

**Comment by keithah** [comment]
We need a log:
https://forums.plex.tv/discussion/246913/getting-kodi-logs

Also stuff like this should be posted on the forum, until we can confirm its a code issue.

**Comment by Enigma0** [comment]
I don't have any logs for it at the moment but it should be really easy to reproduce. Just start a TV Show playlist and let it go for a about 5 or so TV Shows (I don't have an exact count on when it stops).

After it stops it just sits on the 'coming up next' screen but doesn't do the countdown to play the next episode.

Is it intended that it stops auto-playing the next in a shuffle list after a time? If not, then I don't see the point of going to a forum post/feature request model. The Android app doesn't stop so I thought it was safe to assume this addon shouldn't either.

Additionally, if I manually click play for the next item (on the 'coming up next screen') it will play but it will stop back at the 'coming up next' screen after each subsequent episode.

**Comment by keithah** [comment]
I've just got confirmation that it is 'by design' as per Plex's spec, so this isn't an issue.

We do want bug reports, but let's keep them on the forum until their confirmed to be a code issue, since its a better place to have discussion about this (and easier for others to chime in)

Thanks!
