### ISSUE TITLE
pre-play screen: next episode starts even when the TV is turn off

### ISSUE THREAD

**Issue by Skaronator** [plexinc/plex-for-kodi#67]
We have a Sony TV with Android TV as OS. 

Thats a pretty weird issue. If you watch a episode then it'll show the pre-play screen with a countdown to start the next episode and if you turn off the TV in this time frame it'll still start this episode and play it normally even the fact that the TV is turned off (well the OS still runs, I know).

Reproducing:
1. Play a Episode (S01E01)
2. After the end of E01 it'll show E02 and start a countdown
3. Turn off TV before the countdown hits 0
4. Watch on PC the Plex Status and you'll that it starts playing E02

I also tried a other scenario: Turning off the TV while playing a episode and it'll close the video player and display the normal episode page after turning on again.

If you ask me I'd make a `if ()` condition after the countdown that checks if the TV is on.

I'll try to get some logs tomorrow its already 3am :P

**Comment by ruuk** [comment]
There's no way to detect if the TV is on - the add-on knows nothing about the TV.

**Comment by Skaronator** [comment]
How about key input? If there is any key input it could stop the countdown but not sure how android TV handle the power button. (and passthrough it to the apps)

**Comment by ruuk** [comment]
Key input already stops the countdown

**Comment by Skaronator** [comment]
Okay then the power button is not passed to the apps.

Well the dirtiest way (if possible, no clue about kodi): starting a blank video in the background and make a eventhandler that is triggered when the video in background stop. When you turn off the TV it'll stop the video which triggers the eventhandler that stop the countdown.

Pretty dirty..

**Comment by keithah** [comment]
Thats assuming we even get the tv power button, and its consistent. There's no way to know, since usually the kodi device has nothing to do with the TV, so just like if you play a video on a ps4/xbox/etc and turn off your tv, it'll still play. Closing this issue out since its outside of our control.

**Comment by Skaronator** [comment]
But pressing the power button **while** playing a video actually stop the video.
