### ISSUE TITLE
Improve the experience for 21:9 users

### ISSUE THREAD

**Issue by keithah** [plexinc/plex-for-kodi#69]
21:9 users currently have a subpar stretched screen experience:

![](https://us.v-cdn.net/6025034/uploads/editor/pf/0dhoujre9m2z.png)

ref: https://forums.plex.tv/discussion/comment/1350784/#Comment_1350784

Might need more assets from Plex?

**Comment by Skaronator** [comment]
Here is a better example: ![[link](https://gfycat.com/WellmadeRewardingAmericanwirehair)](https://thumbs.gfycat.com/WellmadeRewardingAmericanwirehair-poster.jpg)

The Cover Image is scaling but the tile doesn't scale.

**Comment by ruuk** [comment]
Unfortunately, Kodi for the most part uses absolute positioning/scaling. Images in a control have various scaling options, but there is almost no dynamic layout functionality for controls themselves, which is why the items in the screenshot appear as they do. The only real way accommodate these displays would be to create custom versions of all the screens. This would involve literally dozens of hours of changes as every control element would need to be scaled by hand in the window XMLs (the Home screen alone is over 8000 lines of XML) as well as code changes, not to mention the fact that this means doubling the skin maintenance for the add-on. I don't see us being able to do this.

**Comment by Skaronator** [comment]
Already noticed, that the Kodi interface isn't responsive at all - really embarrassing. At least 21:9 would be good for the future when this addon hits beta/final.

**Comment by danjames92** [comment]
So just to clarify, while other clients such as Plex Media Player have been confirmed to be supporting the 21:9 aspect ratio in terms of its GUI the future, it's not inside the scope for this one? Even with the additional funding provided to the project (or so Keith has mentioned) now that you two are a part of the Plex team?

**Comment by keithah** [comment]
This is a Kodi limitation. We would need to add elements specifically for that aspect ratio and drive unlike PMP this is not a desktop focused product, until 21:9 TV's come out, we went be tripling the amount of work to support it.

**Comment by danjames92** [comment]
>This is a Kodi limitation. We would need to add elements specifically for that aspect ratio and drive unlike PMP this is not a desktop focused product, until 21:9 TV's come out, we went be tripling the amount of work to support it.

Hmm with all due respect Keith that doesn't answer my questions. According to what @ruuk has written above it's implied that it's something that wasn't thought about during development and sounds like it can be worked around if given appropriate resources / time to it. 
Is there something us users can do to make it easier to implement? 

I guess it just ultimately depends if the Plex team think the use case is worth pursuing. Desktop use isn't the _only_ use case. I'm sure plenty of people who have home cinemas use projectors and 21:9 screens with Kodi. That's another use case right there. 

Interestingly default Estuary in Kodi scales perfectly to 21:9. (never tried it out before).
![kodi_2017-04-17_11-39-08](https://cloud.githubusercontent.com/assets/16107603/25086840/cda955ce-2362-11e7-920e-562b47b82b26.jpg)

I was more curious at why the add-on didn't translate well to 21:9 and if it's worth revisiting the idea of it seeing as there is a target audience and last time I checked "10ft tv interfaces" also included enthusiast grade equipment. :)

**Comment by keithah** [comment]
It doesn't 'scale to'. It has design elements added, custom, specifically for 21:9. As Ruuk said, it would take modifying 8000 lines of XML *for the home screen alone*, because the add-on system was not designed with scaling in mind, which is why it's a limitation. 16:9 is hardcoded, 4:3 is hardcoded, 21:9 would have to be too.

Ruuk did not imply it was not something that was not thought about. It was something that, as a TV-based interface and no 21:9 TV's exist, we did not feel tripling the amount of the work is worth the small amount of users who will use it in 21:9 monitors, which is not the intended usage of the app.

In addition, Plex did not have assets for 21:9 at the time of development, so even considering it was off the table, they don't even exist today. Someday, PMP might support it. You realize PMP has more than 1 guy working on it part-time right? Ruuk and myself aren't getting paid solely to work on this add-on, we're both heavily involved in other projects as well, which have far more urgency (and users!)

I have not heard of a single user having a 21:9 projector using this add-on yet. But even if they did, it would be so few, that it wouldn't matter. 

This is also *not* code related, so please, leave chatter like this off GitHub. You can open up a forum thread and we can debate it there, but this is not the intended use of how we'd like to use GitHub.

**Comment by danjames92** [comment]
Will do. Thank you for the explanation.
