### ISSUE TITLE
Sometimes start the media in background.

### ISSUE THREAD

**Issue by vampywiz17** [plexinc/plex-for-kodi#72]
Hello there,

I installed the Plex for Kodi (OSMC - Pi2) but sometimes the media start it in the backround. (i hear the sound, but no picture, only the menu and the menu is lagging) 

The only way to close the movie, that i restart kodi.

**Comment by keithah** [comment]
Try LibreELEC.

**Comment by vampywiz17** [comment]
Yes, i reinstall my Pi2 (latest LibreELEC beta) and the Plex for kodi work well :)
