### ISSUE TITLE
Precaching posters / album art.

### ISSUE THREAD

**Issue by danjames92** [plexinc/plex-for-kodi#73]
This is a feature of OpenPHT (ergo Plex Home Theater) that could be really useful for low powered devices like Raspberry Pi / Odroid's. Currently I believe there is no caching done and it's all being pulled adding delay to displaying the content? Can take a few seconds and that's on a gigabit wired network.

**Comment by keithah** [comment]
It currently caches first time pulled down, which is why on a fresh install its much slower.
