### ISSUE TITLE
black horizontal stripes wont dispear after playback. (only with skin: Eminence 2)

### ISSUE THREAD

**Issue by orengriffin** [plexinc/plex-for-kodi#74]
os: Openelec 7.0.1.
kodi: 16.1
skin: Eminence 2.

i am not sure how to call these stripes, they have some movie info, and on other skins they go away and let the video be shown correctly. on Eminence the stripes wont go off and block big part of the movie. ESC or any other button wont remove it either.

![img_20170203_233016](https://cloud.githubusercontent.com/assets/7240295/22609281/44262f0c-ea69-11e6-9726-134e1991cb52.jpg)

Edit: this issue was also reported in the UX / UI forum by jenkinsmorgan04 on page 1.
Edit #2: added log error:
:3037356032   ERROR: Control 1001 in window 13005 has been asked to focus, but it can't

**Comment by keithah** [comment]
We don't support any other skins besides default ones.
