### ISSUE TITLE
Skip Next media key is ignored

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-for-kodi#77]
Skip Next media key is ignored when trying to skip to the next item in a playlist. The native Plex android app does recognize it however.

Ubuntu GNOME 16.10

**Comment by Skaronator** [comment]
Yup can confirm this.

![image](https://cloud.githubusercontent.com/assets/2886913/22853125/0f10a758-f04e-11e6-8fe4-276e44d90da8.png)


Are the Key Press logged? So I could press those buttons and get the log.

**Comment by Enigma0** [comment]
Might be related: Pressing Play button on an item doesn't seem to play it like with PlexMediaPlayer.

**Comment by ruuk** [comment]
@Enigma0: You don't mention what kind of remote/controller/keyboard you are using.

@Skaronator: I see a Sony remote in your screenshot, but I don't know how this is working in Kodi. Is this a Sony Android TV, are you using CEC, are you using a Flirc adapter or something else?

Also it's useful to know if it works when playing a video in Kodi outside the add-on.

A log with debug logging enabled in Kodi settings _should_ log the key presses.

**Comment by Enigma0** [comment]
@ruuk I am programming media keys, play, pause, stop, skip next, skip previous with Flirc.

Doesn't work in Kodi either. (Ubuntu GNOME 16.10)

**Comment by keithah** [comment]
If it doesn't work in Kodi, it's not a Plex for Kodi issue, since we just use what Kodi uses. You need to get it working in Kodi, and then it will work in the add-on. Closing this out.
