### ISSUE TITLE
Q: Code "Exit Plex" Button

### ISSUE THREAD

**Issue by Skaronator** [plexinc/plex-for-kodi#78]
I've added a button in the Exit Dialog to close Kodi directly but I'm struggling to find the code that is executed when you press the Buttons.

![image](https://cloud.githubusercontent.com/assets/2886913/22853142/9353970a-f04e-11e6-9b83-04f75cfe5734.png)

If I get it right the whole main loop wait in this [line](https://github.com/plexinc/plex-for-kodi/blob/master/lib/main.py#L90) `windowutils.HOME = home.HomeWindow.open()` and the loop continue if you press the exit button and then execute the close part in `finally`.

Buuut I don't get it why it stop there. I can't even find the `open()` function in the `HomeWindow` class?

**Comment by keithah** [comment]
It might be easier if you pointed at your branch of code that @ruuk could review.
