### ISSUE TITLE
Ui glitch and Plex Server think, that 2 videos are played at the same time

### ISSUE THREAD

**Issue by Skaronator** [plexinc/plex-for-kodi#79]
Okay this is a pretty weird issue - don't know where to start first. There are two bugs but I think the second bug was caused because of the first one.

**I'll need to reproduce it but gonna post it for now.**

# UI Bug
I was in the audio setting while playing this episode. I switched to audip passthrough and was surprised, that it worked (since Kodi 17 and Android 5 API). I was remembering, that german audio is just AC3 so decided to switch to english and then want to switch back and it didn't switch:

https://gfycat.com/IdealisticCalmDaddylonglegs

The Video focus is.. yeah not on point but you can see, that `english` is pre-selected and I tried to switch back to `german` but it didn't want to switch. Tried again and again, not want to switch back.

**This might be important: After the first bug I was log out (back to In-Home switch screen) and turn off the TV but Kodi was still open!**

# 2 playbacks at the same time (bug)

Fast forward: 8h later, still the same Plex for Kodi instance open. My parents switch to their account and watch a single episode of Game of Thrones and I was looking in the Plex Web (stalking :P) and notice, that **2 videos are playing at the same time at the same time on the same device**.

Here the Video of Plex Web: https://gfycat.com/InsidiousCelebratedEeve (pressing F5 and you can see, that the watch status is moving)

Might be important to say, that it is playing the same episode of Shameless where I had the UI bug and not the "newer" "On-Deck" episode.

Here is the Plex Web Log: https://gfycat.com/TallTerribleAsiansmallclawedotter (take a look at the time!)

**I assum, that the Shameless episode somehow stuck the playback backend due to the UI bug. Also Important, that the Plex Web log says that I, Skaronator, played GoT instead of my parents account but switching to my parents account it actually saved the correct episode**

## Log

Since this Plex instance run over 24h the log is massive. The UI Bug with the Shameless Episode occur around 08:11 (it's AM) and the GoT Episode was around 8 hours later, ~17:00 (you can see the time in the 3rd video)

[kodi.zip](https://github.com/plexinc/plex-for-kodi/files/769552/kodi.zip)

There are also some log error while Kodi was in background/TV was "off".

I hope the english is fine, pretty long text actually.

**Comment by keithah** [comment]
Sorry in the delay of response. This is quite a strange issue and I think it might just be a 'glitch in the matrix' and not much we can do about it, since it's so hard to replicate.

**Comment by Skaronator** [comment]
Yup I was unable to reproduce it as well. There are some script errors in the log that you could fix.
