### ISSUE TITLE
Kodi hangs when attempting playback

### ISSUE THREAD

**Issue by robdennehy** [plexinc/plex-for-kodi#80]
Whenever I select an item to play, the menus disappear as you'd expect, the blurred yellow background remains but nothing else happens. No playback, no error message. The only way out is to kill the Kodi process.

Additionally, no artwork is showing, I only get the grey placeholders. I am not sure if this could be related.

The server is on the same machine, other clients on other devices are working fine. Kodi is playing other files from elsewhere fine. I am on Linux Mint 18.1 running Kodi 17.0. I can provide the log file but want to know if there is anything in it that I shouldn't post publicly first (plex api key or soemthing).

Thanks.

**Comment by ruuk** [comment]
While the add-on doesn't log any keys, Kodi itself may log playback or image URLs depending on the device and logging settings. If you don't want to manually examine and clean the logs, feel free to email me a log at `xbmc at 2ndmind dot net`

**Comment by robdennehy** [comment]
Thanks for getting back to me. I have emailed you with three log files. 
When reproducing the issue to generate the logs, I encountered another couple of issues that may or may not be related. The steps I look and have log files for are:

- I opened Kodi and then the plex addon. It opened, connected to my server but displaying no items at all. I tried searching for something I knew to exist and did get results. The thumbnails for all results were grey placeholders. I closed Kodi and it hung upon edit and the process had to be killed.

- I opened Kodi and then the plex addon, it now wanted to authorise but said it couldn't connect to plex.tv. This had happened before, and usually sorts itself on repeated openings. I had to do this perhaps 8 times before it worked, attached is one log file from such an instance of failure.

- I opened and successfully authorised with plex.tv. It opened my library to display current items correctly, but with only grey placeholder thumbs. When I attempted playback it just showed the yellow background until I killed the kodi process.

I hope I've not muddied the issue with other problems, but in case they are somehow related I thought best to include all.

**Comment by keithah** [comment]
I bet it's because Mint uses the latest and greatest Python, and Kodi tries to use it. There's some instructions on the forum to downgrade your python and work around until Kodi updates it to latest.

**Comment by robdennehy** [comment]
Mint has got v2.7 of Python installed so I doubt it's that unfortunately. Also, I couldn't find those instructions, any chance of a link so I can check it out just in case?

**Comment by keithah** [comment]
Mint apparently tries to install v18, which is not even in alpha:
https://forums.plex.tv/discussion/comment/1382132#Comment_1382132

Or it might be this:
https://forums.plex.tv/discussion/259607/plex-addon-crashes-kodi-17-0
