### ISSUE TITLE
Every video needs an audio adjustement

### ISSUE THREAD

**Issue by acs-ferreira** [plexinc/plex-for-kodi#82]
When i read my files trough Plex on my LG Smart TV or on Browser, everything runs smooth.

On Plex for Kodi, i need to manually apply an audio adjustment (trough Kodi) of `+0.125s` to sync audio and image, on every single file.

Kodi `1.7` and Plex for Kodi `v0.0.101`.

**Comment by ruuk** [comment]
It sounds like you need to set the offset as the default for all media in Kodi. In the dialog where you set the option for this there is an option at the bottom to do this. Without any other info, my guess is that your TV's image processing is introducing a delay which is not present in whatever your audio path is from Kodi. Presumably any video played within Kodi will have this issue. As I don't think this an issue with the add-on (from the info I have at hand) I'm going to close this issue. Feel free to re-open it if you have reason to believe the add-on is the source of the problem.
