### ISSUE TITLE
FEATURE REQUEST - Allow use of 3rd party plugins

### ISSUE THREAD

**Issue by qazero** [plexinc/plex-for-kodi#89]
Is there any way to use 3rd party plugins such the Kodi opensubtitles plugin? I know plex has a feature to download subtitles automatically from opensubtitles, however, many times the incorrect subtitles are downloaded. Being able to use the kodi opensubtitles plugin would be great since it displays a list of relevant subtitles to choose from. This would be great to try additional subtitles in the event the default plex downloaded subtitles are out of sync.

**Comment by keithah** [comment]
This is not the place to ask this, and the answer is yes, this is already supported. See the FAQ in the forum. Closing this ticket out, since it's a generic support question and not code related.
