### ISSUE TITLE
Sorting doesn't save in the latest build (v102)

### ISSUE THREAD

**Issue by keithah** [plexinc/plex-for-kodi#94]
I haven't had a chance to verify, but according to a user sorting does not save when using v102, when it did for v101:
One of my libraries is TV Shows. With v101 I was able to sort it by 'Unwatched', 'Date Added'. I could leave the library, come back and those parameters are retained. However, with v102b it would revert back to the default - 'All', 'Title'.

ref: https://forums.plex.tv/discussion/comment/1414788/#Comment_1414788

**Comment by ruuk** [comment]
Found the issues. Fixing it :)

**Comment by ruuk** [comment]
Fixed for v0.0.102b2
