### ISSUE TITLE
Display full audio codec names.

### ISSUE THREAD

**Issue by danjames92** [plexinc/plex-for-kodi#97]
Currently the full codec names of the audio tracks are absent with all variations of DTS blanketed under the term DTS. While I can see a audio track has for example 1080p | DTS | 7.1 I cannot tell whether it's a core track or a full HD track.

I believe the only client I use on a regular basis that has these names listed correctly is the Android TV client as seen below and even then DTS-HD HRA is listed and DTS and so is DTS-ES. If TrueHD can be listed as such in the addon and in other clients, I don't see why all kinds of DTS should be blanketed particularly as the Android TV app doesn't do this.

While Plex seem to be shying away from displaying this information in Plex Web with the removal of these logos and information, I would like to see the full names per codec i.e. DTS-HD MA, DTS-HD HRA, DTS-ES make a return.

![img_0443](https://cloud.githubusercontent.com/assets/16107603/25075100/1a0bea4e-2304-11e7-92a8-51c7d9197eca.JPG)

Thanks for considering.

**Comment by keithah** [comment]
When displaying info about a piece of media, Plex reports the maximum number of possible channels, such as "DTS 5.1", "DTS 6.1", or "DTS 7.1", but does not report the specific flavor of DTS. Note that this is the maximum number of channels possible for the file, and your device may play fewer channels – 5.1 or stereo – depending on its capabilities.
While the metadata always shows the correct number of channels, the UI won't show the specific flavor of DTS. Plex has made a design decision to only show the codec name that is actually contained in the video file headers, which is "DTS" in all cases.

**Comment by danjames92** [comment]
I guess the question becomes is why isn't the design consistent throughout all clients then. Odd.

Thanks for the explanation. 👍
